/**
 * 30 curated locations for the GeoGuesser party game.
 * Index 0 (Eiffel Tower) is always used as the demo round.
 * The rest are shuffled and a subset is picked for actual rounds.
 *
 * Each location has:
 *  - name: display name (revealed after round)
 *  - lat, lng: exact coordinates
 *  - hint: fallback clue (only shown if Street View fails)
 *  - heading: initial Street View camera heading (0–360)
 *  - category: emoji + label
 *  - difficulty: 'Easy' or 'Medium'
 *  - greeting: "Hello/Good morning" in actual native script
 *  - flag: country flag emoji
 *  - placeShort: short name of the place (excluding country/city)
 *  - countryCode: 2-letter lowercase ISO country code for Flagcdn
 */
const LOCATIONS = [
  // ── 0: DEMO ROUND (always first) ──────────────────────────────
  {
    name: "Eiffel Tower, Paris",
    lat: 48.8566,
    lng: 2.2980,
    heading: 310,
    hint: "This 'Iron Lady' was built as a temporary exhibit for a World's Fair but became the world's most visited paid monument 🇫🇷",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "Bonjour",
    flag: "🇫🇷",
    placeShort: "Eiffel Tower",
    countryCode: "fr",
  },

  // ── 1–29: GAME ROUNDS (shuffled) ──────────────────────────────
  {
    name: "Taj Mahal, Agra",
    lat: 27.1739,
    lng: 78.0421,
    heading: 0,
    hint: "An emperor built this white marble masterpiece as an eternal symbol of love for his wife 🇮🇳",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "नमस्ते",
    flag: "🇮🇳",
    placeShort: "Taj Mahal",
    countryCode: "in",
  },
  {
    name: "Statue of Liberty, New York",
    lat: 40.6898,
    lng: -74.0453,
    heading: 130,
    hint: "A gift between two countries, this copper lady holds a torch and a tablet inscribed with July 4, 1776 🗽",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "Hello",
    flag: "🇺🇸",
    placeShort: "Statue of Liberty",
    countryCode: "us",
  },
  {
    name: "Great Wall of China",
    lat: 40.4301,
    lng: 116.5617,
    heading: 90,
    hint: "This ancient defensive fortification is so massive it was once believed to be visible from space 🇨🇳",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "你好",
    flag: "🇨🇳",
    placeShort: "Great Wall of China",
    countryCode: "cn",
  },
  {
    name: "Colosseum, Rome",
    lat: 41.8906,
    lng: 12.4907,
    heading: 120,
    hint: "Ancient gladiators once fought in this 50,000-seat arena, the largest amphitheater ever built 🇮🇹",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "Ciao",
    flag: "🇮🇹",
    placeShort: "Colosseum",
    countryCode: "it",
  },
  {
    name: "Machu Picchu, Peru",
    lat: -13.1629,
    lng: -72.5452,
    heading: 350,
    hint: "This 'Lost City' of an ancient empire sits 2,430 meters above sea level in the clouds ☁️",
    category: "🏔️ Natural Wonder",
    difficulty: "Medium",
    greeting: "Allianllachu / Hola",
    flag: "🇵🇪",
    placeShort: "Machu Picchu",
    countryCode: "pe",
  },
  {
    name: "Sydney Opera House, Australia",
    lat: -33.8573,
    lng: 151.2124,
    heading: 60,
    hint: "This performing arts center's distinctive sail-shaped roof makes it one of the most photographed buildings in the Southern Hemisphere 🇦🇺",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "G'day",
    flag: "🇦🇺",
    placeShort: "Sydney Opera House",
    countryCode: "au",
  },
  {
    name: "Christ the Redeemer, Rio de Janeiro",
    lat: -22.9523,
    lng: -43.2107,
    heading: 30,
    hint: "This 30-meter Art Deco statue stands atop a 700-meter peak, arms spread wide over a carnival-loving city 🇧🇷",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "Olá",
    flag: "🇧🇷",
    placeShort: "Christ the Redeemer",
    countryCode: "br",
  },
  {
    name: "Pyramids of Giza, Egypt",
    lat: 29.9753,
    lng: 31.1376,
    heading: 290,
    hint: "The last surviving Wonder of the Ancient World, these structures were the tallest man-made objects for 3,800 years 🏜️",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "مرحبًا",
    flag: "🇪🇬",
    placeShort: "Pyramids of Giza",
    countryCode: "eg",
  },
  {
    name: "Big Ben, London",
    lat: 51.5008,
    lng: -0.1221,
    heading: 260,
    hint: "This iconic clock tower's bell weighs 13.5 tons and has been keeping time since 1859 🇬🇧",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "Hello",
    flag: "🇬🇧",
    placeShort: "Big Ben",
    countryCode: "gb",
  },
  {
    name: "Mount Fuji, Japan",
    lat: 35.4950,
    lng: 138.8025,
    heading: 220,
    hint: "This sacred, snow-capped volcano is the highest peak in its island nation and a symbol of its culture 🗻",
    category: "🏔️ Natural Wonder",
    difficulty: "Easy",
    greeting: "こんにちは",
    flag: "🇯🇵",
    placeShort: "Mount Fuji",
    countryCode: "jp",
  },
  {
    name: "Santorini, Greece",
    lat: 36.4615,
    lng: 25.3752,
    heading: 230,
    hint: "This volcanic island is famous for white-washed buildings with blue domes overlooking a sunken caldera 🇬🇷",
    category: "🌍 Famous Place",
    difficulty: "Medium",
    greeting: "Γειά σου",
    flag: "🇬🇷",
    placeShort: "Santorini",
    countryCode: "gr",
  },
  {
    name: "Niagara Falls, USA/Canada",
    lat: 43.0792,
    lng: -79.0775,
    heading: 100,
    hint: "These thundering waterfalls on an international border have been a honeymoon destination since the early 1800s 💧",
    category: "🏔️ Natural Wonder",
    difficulty: "Easy",
    greeting: "Hello / Bonjour",
    flag: "🇨🇦",
    placeShort: "Niagara Falls",
    countryCode: "ca",
  },
  {
    name: "Petra, Jordan",
    lat: 30.3221,
    lng: 35.4516,
    heading: 260,
    hint: "This ancient city carved into rose-red cliffs was featured as the resting place of the Holy Grail in an Indiana Jones film 🎬",
    category: "🏛️ Monument",
    difficulty: "Medium",
    greeting: "مرحبًا",
    flag: "🇯🇴",
    placeShort: "Petra",
    countryCode: "jo",
  },
  {
    name: "Golden Gate Bridge, San Francisco",
    lat: 37.8282,
    lng: -122.4833,
    heading: 140,
    hint: "When it opened in 1937, this 2.7 km suspension bridge painted in 'International Orange' was the longest in the world 🌉",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "Hello",
    flag: "🇺🇸",
    placeShort: "Golden Gate Bridge",
    countryCode: "us",
  },
  {
    name: "Angkor Wat, Cambodia",
    lat: 13.4125,
    lng: 103.8637,
    heading: 90,
    hint: "The world's largest religious monument, this 12th-century temple was originally dedicated to the Hindu god Vishnu 🇰🇭",
    category: "🏛️ Monument",
    difficulty: "Medium",
    greeting: "ជំរាបសួរ",
    flag: "🇰🇭",
    placeShort: "Angkor Wat",
    countryCode: "kh",
  },
  {
    name: "Burj Khalifa, Dubai",
    lat: 25.1963,
    lng: 55.2786,
    heading: 280,
    hint: "At 828 meters, this skyscraper held the 'world's tallest building' record since 2010 and has 163 floors 🏙️",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "مرحبًا",
    flag: "🇦🇪",
    placeShort: "Burj Khalifa",
    countryCode: "ae",
  },
  {
    name: "Stonehenge, England",
    lat: 51.1789,
    lng: -1.8262,
    heading: 0,
    hint: "These mysterious 25-ton stones were placed in a circular formation around 5,000 years ago — nobody knows exactly why 🪨",
    category: "🏛️ Monument",
    difficulty: "Medium",
    greeting: "Hello",
    flag: "🇬🇧",
    placeShort: "Stonehenge",
    countryCode: "gb",
  },
  {
    name: "Venice, Italy",
    lat: 45.4380,
    lng: 12.3359,
    heading: 90,
    hint: "This city built on 118 small islands uses gondolas and water buses instead of cars and regular buses 🛶",
    category: "🌍 Famous Place",
    difficulty: "Easy",
    greeting: "Ciao",
    flag: "🇮🇹",
    placeShort: "Venice",
    countryCode: "it",
  },
  {
    name: "Grand Canyon, USA",
    lat: 36.0616,
    lng: -112.1079,
    heading: 355,
    hint: "The Colorado River spent 5–6 million years carving this 446 km long, 1.6 km deep geological wonder 🏜️",
    category: "🏔️ Natural Wonder",
    difficulty: "Medium",
    greeting: "Hello",
    flag: "🇺🇸",
    placeShort: "Grand Canyon",
    countryCode: "us",
  },
  {
    name: "Table Mountain, Cape Town",
    lat: -33.9068,
    lng: 18.4215,
    heading: 190,
    hint: "This flat-topped mountain often wears a 'tablecloth' of clouds and overlooks where two oceans meet 🇿🇦",
    category: "🏔️ Natural Wonder",
    difficulty: "Medium",
    greeting: "Molo / Sawubona",
    flag: "🇿🇦",
    placeShort: "Table Mountain",
    countryCode: "za",
  },
  {
    name: "The Kremlin, Moscow",
    lat: 55.7540,
    lng: 37.6205,
    heading: 140,
    hint: "This medieval fortified complex with red walls and golden domes serves as the official residence of a world leader 🇷🇺",
    category: "🏛️ Monument",
    difficulty: "Medium",
    greeting: "Здравствуйте",
    flag: "🇷🇺",
    placeShort: "The Kremlin",
    countryCode: "ru",
  },
  {
    name: "Chichén Itzá, Mexico",
    lat: 20.6830,
    lng: -88.5686,
    heading: 40,
    hint: "During equinox, shadows create the illusion of a serpent slithering down this ancient pyramid's staircase 🐍",
    category: "🏛️ Monument",
    difficulty: "Medium",
    greeting: "Ba'ax ka wa'alik / Hola",
    flag: "🇲🇽",
    placeShort: "Chichén Itzá",
    countryCode: "mx",
  },
  {
    name: "Great Barrier Reef, Australia",
    lat: -23.4429,
    lng: 151.9135,
    heading: 180,
    hint: "The world's largest living structure, this 2,300 km coral system is visible from space 🐠",
    category: "🏔️ Natural Wonder",
    difficulty: "Medium",
    greeting: "G'day",
    flag: "🇦🇺",
    placeShort: "Great Barrier Reef",
    countryCode: "au",
  },
  {
    name: "Hobbiton, New Zealand",
    lat: -37.8721,
    lng: 175.6829,
    heading: 310,
    hint: "This real movie set in rolling green farmland was built for one of the highest-grossing fantasy film trilogies ever 🧙",
    category: "🎬 Movie Location",
    difficulty: "Medium",
    greeting: "Kia ora",
    flag: "🇳🇿",
    placeShort: "Hobbiton",
    countryCode: "nz",
  },
  {
    name: "Leaning Tower of Pisa, Italy",
    lat: 43.7229,
    lng: 10.3958,
    heading: 70,
    hint: "This bell tower took 199 years to build and has been unintentionally tilting since construction began in 1173 🇮🇹",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "Ciao",
    flag: "🇮🇹",
    placeShort: "Leaning Tower of Pisa",
    countryCode: "it",
  },
  {
    name: "Maldives",
    lat: 4.4542,
    lng: 73.7168,
    heading: 270,
    hint: "This island nation of 1,192 coral islands is the world's lowest-lying country, averaging just 1.5 m above sea level 🏝️",
    category: "🌍 Famous Place",
    difficulty: "Medium",
    greeting: "Assalaamu Alaikum",
    flag: "🇲🇻",
    placeShort: "Maldives",
    countryCode: "mv",
  },
  {
    name: "Reykjavik, Iceland",
    lat: 64.1420,
    lng: -21.9272,
    heading: 110,
    hint: "The world's northernmost capital city, famous for geothermal pools and being a gateway to seeing the Aurora Borealis 🇮🇸",
    category: "🌍 Famous Place",
    difficulty: "Medium",
    greeting: "Góðan daginn",
    flag: "🇮🇸",
    placeShort: "Reykjavik",
    countryCode: "is",
  },
  {
    name: "Manaus, Amazon Rainforest",
    lat: -3.0232,
    lng: -60.4682,
    heading: 270,
    hint: "This city in the heart of the world's largest rainforest has a famous opera house built during a rubber boom 🌳",
    category: "🏔️ Natural Wonder",
    difficulty: "Medium",
    greeting: "Olá",
    flag: "🇧🇷",
    placeShort: "Amazon Rainforest",
    countryCode: "br",
  },
  {
    name: "Banff National Park, Canada",
    lat: 51.3217,
    lng: -116.1860,
    heading: 210,
    hint: "This park in the Canadian Rockies features turquoise glacier-fed lakes and was the country's first national park 🇨🇦",
    category: "🏔️ Natural Wonder",
    difficulty: "Medium",
    greeting: "Hello",
    flag: "🇨🇦",
    placeShort: "Banff National Park",
    countryCode: "ca",
  },
  {
    name: "Hawa Mahal, Jaipur",
    lat: 26.9242,
    lng: 75.8268,
    heading: 240,
    hint: "This 'Palace of Winds' features a unique five-story pink sandstone facade with 953 small windows designed for royal women to observe street life 🇮🇳",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "नमस्ते",
    flag: "🇮🇳",
    placeShort: "Hawa Mahal",
    countryCode: "in",
  },
  {
    name: "Gateway of India, Mumbai",
    lat: 18.9218,
    lng: 72.8346,
    heading: 0,
    hint: "Built to commemorate the landing of King George V and Queen Mary in 1911, this basalt arch stands on the waterfront in Bombay 🇮🇳",
    category: "🏛️ Monument",
    difficulty: "Easy",
    greeting: "नमस्ते",
    flag: "🇮🇳",
    placeShort: "Gateway of India",
    countryCode: "in",
  },
];
